### ISSUE TITLE
[JOSS-review] Paper and package claims

### ISSUE THREAD

**Issue by mschubert** [fellstat/ipc#9]
related: https://github.com/openjournals/joss-reviews/issues/988

I think the use of this package to develop responsive applications is very well supported, and as far as I can tell this was the reason this package was developed in the first place (commit history also lists the previous name as `ShinyAsyncTools`). It is definitely useful as such, and the `shiny` and `future` examples using the progress bar instead of the application becoming unresponsive illustrate this nicely.

However, it looks to me like the paper introduction and statement of need can be improved, to focus more on the packages strengths and not over-claim its novelty. In particular:

* [x] *Currently the statistical computing language R provides no built in features to handle interprocess communication.*
What about the `parallel` or `snow` packages? They do provide communication between processes. `parallel:::sendCall` is also able to send individual instructions to workers (it is not exported, but it exists)
* [x] *What is lacking is a framework to easily pass R objects between processes along with an associated signal, and have handler functions automatically execute them in the receiving process.*
Doesn't [`rmote`](https://github.com/cloudyr/rmote) do this?
* [x] In the [pre-review thread](https://github.com/openjournals/joss-reviews/issues/933#issuecomment-419578414), you stated *Often research requires computationally intensive activity. This package supports HPC by making it easy for the researcher to monitor their distributed processing by having child threads report back partial results and progress.*
What is the advantage over using an actual HPC workflow package here, like `drake`? It does distributed processing, progress report, and that without the user having to write their own signals for it.
If this package is suitable for tracking HPC progress as it claims, I would also like to see a performance evaluation (e.g., how many inputs can it process per time interval?).

**Comment by ifellows** [comment]
Thanks for this. The impetus for this package came directly from shiny, however, what came out was quite a bit more general. The name change came at the suggestion of some folks over at rstudio, who felt the package was being done a disservice by the narrow name.

Clearly a I need to give a bit more thought to how I can communicate the non-shiny use cases. Currently there aren't any examples, so it is sort of left to the imagination. I'll add an example to the vignette, and review the paper to make sure the claims are a bit more narrow.

Fundamentally the difference with some of the things you've mentioned is that this package is focused on communication during computation, and in particular reporting information back to the user in an interactive setting. `parallel:::sendCall` is different because it creates a new computation and sends it to be executed, this is different than communicating with an already running computation. `drake` is a full fledged pipeline, whereas `ipc` operates a bit more like a tool that would be used within a pipeline. `rmote` seems (at first glance at least) to focus on forwarding graphical output from a sever to a client.

One use case where I see this package fitting in with regard to HPC is supporting interactive diagnostics and progress for parallelized functions. For example `ergm`, `rstan` and my own package [lolog](https://github.com/statnet/lolog) all have (optional) parallel operations. It would be great if the running diagnostics functioned identically to how they do when the algorithms are run sequentially. `ergm` and `lolog` drop key diagnostics and progress, while `rstan` can optionally emit to a file that you can tail.

Here is a minimal example of how `ipc` can be used to monitor the progress and convergence of parallel MCMC chains:

```
library(parallel)
library(ipc)

mcmcTask <- function(){
  on.exit(q$destroy())
  q <- queue()
  prog <- 1
  pb <- txtProgressBar(min = 0, max = 40, style=3)
  res <- list()
  chains <- list()
  for(i in 1:4){
    res[[i]] <- mcparallel({
      chain <- c()
      for(j in 1:10){
        chain <- c(chain, rnorm(100))
        q$producer$fireEval(chains[[i]] <- chain, list(i=i,chain=chain))
        q$producer$fireEval(prog <- prog + 1)
        Sys.sleep(runif(1)*5)
      }
      chain
    })
  }
  while(prog < 40){
    q$consumer$consume()
    setTxtProgressBar(pb, prog)
    par(mfrow=c(2,2))
    for(j in seq_along(chains)) 
      if(length(chains[[j]]) > 1) 
        plot(chains[[j]], main=paste("Trace Plot for MCMC chain", j))
    Sys.sleep(1)
  }
  close(pb)
  mccollect(res)
}

chains <- mcmcTask()
```

I'll definitely put some changes into the documentation around this, and I think that it bears some thinking as to whether there are some package changes that would be desirable. More to come....

**Comment by ifellows** [comment]
So after some thought, what I'd _like_ to do is see if I can wrap parallel clusters with an associated queue and then have messages automatically consumed as you are running any or the various parallel applys. I think this is possible after some looking into the code.

However, it is beyond the current scope. I've worked over the language in the paper, vignette and readme to make it softer with regard to HPC. I've also added an HPC example to the vignette.

Do these changes and the clarifications in my previous comment adequately address your concerns?

**Comment by mschubert** [comment]
I still don't agree with the sentence

> Currently the statistical computing language R provides no built in features to handle interprocess communication.

What `parallel:::sendCall` does is not the same as `ipc` does, but it *is a* form of communication between active R processes as well (the communication being the call sent).

I'd be happy with replacing *interprocess communication* with *reactive values*, or *status values*, or something else you would think fits (*updating status while running computations*?).

<hr/>
Also, it would be great if your statement of need in the paper included your explanations above. This could be as easy as copy + paste the lines

> the difference <with some of the things you've mentioned> is that this package is focused on communication during computation, and in particular reporting information back to the user in an interactive setting. parallel:::sendCall is different because it creates a new computation and sends it to be executed, this is different than communicating with an already running computation. drake is a full fledged pipeline, whereas ipc operates a bit more like a tool that would be used within a pipeline. rmote seems (at first glance at least) to focus on forwarding graphical output from a sever to a client

and

> One use case where I see this package fitting in with regard to HPC is supporting interactive diagnostics and progress for parallelized functions.

**Comment by ifellows** [comment]
That is why I had changed the sentence to add "between active R processes," to indicate that the use case is for communication between processes that are in the middle of running R computations. To avoid ambiguity, the sentence is now 
> Currently the statistical computing language R provides no built in features to handle interprocess communication between R processes while they are performing computations.

Further, `sendCall` is not an exported function, and therefore could not be said to have been "provided." Not that this matters though, since any parallel functionality *could* be said to be doing interprocess communication. After all, how could you run anything in parallel if you can't communicate what to run?

-----------------------------------

I've added references to `drake` and `parallel` to help contextualize where the package lays within the R ecosystem. I didn't particularly call out `sendCall` as it is not exported and therefore would likely just confuse the reader.

The last sentence before "## Use in Shiny" lays out the HPC use case as requested.

**Comment by mschubert** [comment]
> That is why I had changed the sentence to add "between active R processes,"

Copy/paste error on my part, sorry. My point referred to your updated sentence (as the worker will be started separately, so the worker is running in both cases).

I agree with "provided", but would also argue that if the meaning of your sentence relies on a single word being interpreted correctly, you might want to rephrase in avoid confusion. I would consider myself more knowledgeable than the average user about this topic, and I was confused. How about a user that doesn't know `ipc`, the inner workings of `parallel`, `rzmq`, or `drake`? How should they know if they want to use `ipc` or rather another package? (maybe wait a day, and then re-read your first paper paragraph again - you still may want to clean it up a bit)

> Not that this matters though, since any parallel functionality could be said to be doing interprocess communication. After all, how could you run anything in parallel if you can't communicate what to run?

Yes, that was point of my criticism about positioning `ipc` as *the* way to do inter-process communication.

<hr>

Not mentioning `sendCall` is perfectly fine, as long as the text doesn't pretend the functionality does not exist.

HPC use case looks good.
